services:
  - type: web
    name: portfolio-qwerty3d
    runtime: static
    repo: https://github.com/xtruel/creative-technologist-portfolio
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    previews:
      generation: manual
    envVars:
      - key: NODE_VERSION
        value: 22
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
